name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      OWNER: yekuanyshev
      IMAGE: todo
      TAG: main
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-go@v3
       with:
          go-verion: ">=1.21"

     - name: login ghcr.io
       run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

     - name: build image  
       run: docker build -t ghcr.io/$OWNER/$IMAGE:$TAG .
      
     - name: push image to registry
       run: docker push ghcr.io/$OWNER/$IMAGE:$TAG

     - name: install go-migrate
       run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate
    
     - name: apply migration
       run: DB_DSN="${{ secrets.DB_DSN }}" make migrate_up

     - name: deploy
       run: curl -f -k -X POST ${{ vars.PORTAINER_WEBHOOK }}
